# Generated by Django 3.2.5 on 2024-03-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
