# Generated by Django 3.2.5 on 2024-03-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_sale_global_id_rentalcontract_rent_global_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalcontract',
            name='customer',
        ),
    ]
