# Generated by Django 3.2.5 on 2024-03-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240327_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleunit',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
