# Generated by Django 3.2.5 on 2024-03-29 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240329_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='purchased_vehicles',
            field=models.ManyToManyField(related_name='customer', through='core.Sale', to='core.VehicleUnit'),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='rented_vehicles',
            field=models.ManyToManyField(related_name='rented_by', through='core.RentalContract', to='core.VehicleUnit'),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='rented_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
